namespace HexaEngine.UI.XamlGen
{
    using System;
    using System.Linq;
    using System.Text;

    public class CodeWriter : IDisposable
    {
        private readonly StringBuilder sb;
        private int indentLevel;
        private const string IndentString = "    ";
        private bool shouldIndent = true;
        private int blocks = 0;

        public CodeWriter(StringBuilder sb, string @namespace, params string[] usings)
        {
            this.sb = sb;
            indentLevel = 0;
            sb.AppendLine("// ------------------------------------------------------------------------------");
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     This code was generated by a tool.");
            sb.AppendLine("//");
            sb.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if");
            sb.AppendLine("//     the code is regenerated.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("// ------------------------------------------------------------------------------");
            sb.AppendLine();

            foreach (var u in usings)
            {
                WriteLine($"using {u};");
            }

            if (usings.Any())
            {
                sb.AppendLine();
            }

            BeginBlock($"namespace {@namespace}");
        }
        public int IndentLevel => indentLevel;

        public void Indent(int count) => indentLevel += count;

        public void Unindent(int count)
        {
            indentLevel = Math.Max(0, indentLevel - count);
        }

        public void Write(string text)
        {
            WriteIndented(text);
        }

        private void TryIndent()
        {
            if (shouldIndent)
            {
                for (int i = 0; i < indentLevel; i++)
                {
                    sb.Append(IndentString);
                }
                shouldIndent = false;
            }
        }

        private void WriteIndented(char chr)
        {
            TryIndent();
            sb.Append(chr);
        }

        private void WriteIndented(string text)
        {
            TryIndent();
            sb.Append(text);
        }

        private unsafe void WriteIndented(ReadOnlySpan<char> @string)
        {
            TryIndent();
            fixed (char* ptr = @string)
            {
                sb.Append(ptr, @string.Length);
            }
        }

        public void WriteLine(string line = "")
        {
            WriteIndented(line);
            sb.AppendLine();
            shouldIndent = true;
        }

        public void BeginBlock(string line = "")
        {
            WriteLine(line);
            WriteLine("{");
            Indent(1);
            ++blocks;
        }

        public void EndBlock()
        {
            if (blocks == 0) return;
            --blocks;
            Unindent(1);
            WriteLine("}");
        }

        public readonly struct CodeBlock : IDisposable
        {
            private readonly CodeWriter writer;

            public CodeBlock(CodeWriter writer, string line)
            {
                this.writer = writer;
                writer.BeginBlock(line);
            }

            public readonly void Dispose()
            {
                writer.EndBlock();
            }
        }

        public CodeBlock PushBlock(string line = "") => new(this, line);

        public override string ToString() => sb.ToString();

        public void Dispose()
        {
            EndBlock();
        }
    }
}