// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using HexaEngine.UI;
using HexaEngine.UI.Controls;
using HexaEngine.UI.Graphics;
using HexaEngine.UI.Graphics.Text;
using Hexa.NET.Mathematics;

namespace TestApp
{
    public partial class Test : UIWindow
    {
        public override void InitializeComponent()
        {
            this.Title = "MainWindow";
            this.Height = 720;
            this.Width = 1280;
            this.Background = new SolidColorBrush(new Color(0x2C2C2CFF));
            this.Resources.Add(new Style()
            {
                TargetType = typeof(Label),
            });
            Grid element0 = new();
            element0.ColumnDefinitions.Add(new ColumnDefinition());
            element0.ColumnDefinitions.Add(new ColumnDefinition());
            element0.ColumnDefinitions.Add(new ColumnDefinition());
            element0.RowDefinitions.Add(new RowDefinition());
            element0.RowDefinitions.Add(new RowDefinition());
            element0.RowDefinitions.Add(new RowDefinition());
            StackPanel element1 = new();
            element1.SetValue(Grid.ColumnProperty, 1);
            element1.SetValue(Grid.RowProperty, 1);
            element1.HorizontalAlignment = HorizontalAlignment.Center;
            Label element2 = new();
            element2.Margin = new Thickness(0, 0, 0, 0);
            element2.Foreground = new SolidColorBrush(new Color(0xFFFFFFFF));
            element2.FontSize = 20;
            element2.FontFamilyName = "Cascadia Mono";
            element2.Content = "StackItem 1";
            element1.Children.Add(element2);
            Label element3 = new();
            element3.Margin = new Thickness(0);
            element3.Foreground = new SolidColorBrush(new Color(0xFFFFFFFF));
            element3.FontFamilyName = "Cascadia Mono";
            element3.Content = "StackItem 2";
            element1.Children.Add(element3);
            Label element4 = new();
            element4.Margin = new Thickness(0, 0, 0, 0);
            element4.Foreground = new SolidColorBrush(new Color(0xFFFFFFFF));
            element4.FontFamilyName = "Cascadia Mono";
            element4.Content = "StackItem 3";
            element1.Children.Add(element4);
            TextBox element5 = new();
            element5.MinWidth = 100;
            element5.MinHeight = 40;
            element5.WordWrapping = WordWrapping.Wrap;
            Button element6 = new();
            element6.Content = "Test";
            element1.Children.Add(element6);
            element0.Children.Add(element1);
            this.Content = element0;
            element6.Click += OnButtonClick;
        }
    }
}
