// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using HexaEngine.UI;
using HexaEngine.UI.Controls;
using HexaEngine.UI.Graphics;
using HexaEngine.UI.Graphics.Text;
using Hexa.NET.Mathematics;

namespace TestApp
{
    public partial class Test : Window
    {
        public override void InitializeComponent()
        {
            this.Title = "MainWindow";
            this.Height = 720;
            this.Width = 1280;
            this.Background = new SolidColorBrush(new Color(0x2C2C2CFF));
            Style element0 = new();
            element0.TargetType = typeof(Label);
            Setter element1 = new();
            element1.TargetProperty = global::HexaEngine.UI.Controls.Control.ForegroundProperty;
            element1.Property = "Foreground";
            element1.Value = new SolidColorBrush(new Color(0xFFFFFFFF));
            element0.Setters.Add(element1);
            Setter element2 = new();
            element2.TargetProperty = global::HexaEngine.UI.Controls.Control.FontFamilyNameProperty;
            element2.Property = "FontFamilyName";
            element2.Value = "Cascadia Mono";
            element0.Setters.Add(element2);
            this.Resources.Add(typeof(Label), element0);
            Style element3 = new();
            element3.TargetType = typeof(Label);
            Setter element4 = new();
            element4.TargetProperty = global::HexaEngine.UI.Controls.Control.ForegroundProperty;
            element4.Property = "Foreground";
            element4.Value = new SolidColorBrush(new Color(0xFF00FFFF));
            element3.Setters.Add(element4);
            this.Resources.Add("TestStyle", element3);
            Grid element5 = new();
            ColumnDefinition element6 = new();
            element5.ColumnDefinitions.Add(element6);
            ColumnDefinition element7 = new();
            element5.ColumnDefinitions.Add(element7);
            ColumnDefinition element8 = new();
            element5.ColumnDefinitions.Add(element8);
            RowDefinition element9 = new();
            element5.RowDefinitions.Add(element9);
            RowDefinition element10 = new();
            element5.RowDefinitions.Add(element10);
            RowDefinition element11 = new();
            element5.RowDefinitions.Add(element11);
            StackPanel element12 = new();
            element12.SetValue(Grid.ColumnProperty, 1);
            element12.SetValue(Grid.RowProperty, 1);
            element12.HorizontalAlignment = HorizontalAlignment.Center;
            Label element13 = new();
            element13.Margin = new Thickness(0, 0, 0, 0);
            element13.FontSize = 20;
            element13.Content = "StackItem 1";
            element12.Children.Add(element13);
            Label element14 = new();
            element14.Style = (global::HexaEngine.UI.Style)this.FindResource("TestStyle")!;
            element14.Margin = new Thickness(0);
            element14.FontFamilyName = "Cascadia Mono";
            element14.Content = "StackItem 2";
            element12.Children.Add(element14);
            Label element15 = new();
            element15.Margin = new Thickness(0, 0, 0, 0);
            element15.Foreground = new SolidColorBrush(new Color(0xFFFFFFFF));
            element15.FontFamilyName = "Cascadia Mono";
            element15.Content = "StackItem 3";
            element12.Children.Add(element15);
            TextBox element16 = new();
            element16.MinWidth = 100;
            element16.MinHeight = 40;
            element16.WordWrapping = WordWrapping.Wrap;
            element12.Children.Add(element16);
            Button element17 = new();
            element17.Content = "Test";
            element12.Children.Add(element17);
            element5.Children.Add(element12);
            TextBox element18 = new();
            element18.Width = 120;
            element18.WordWrapping = WordWrapping.WrapWord;
            element18.AcceptsReturn = true;
            element18.FontFamilyName = "Cascadia Mono";
            element18.Text = "one two three four five six seven eight nine ten eleven twelve thirteen fourteen fifteen sixteen seventeen eighteen nineteen twenty";
            element5.Children.Add(element18);
            this.Content = element5;
            element17.Click += OnButtonClick;
        }
    }
}
